[package]
name = "libimgvwr"
version = "0.1.0"
description = "Core library for the imgvwr image viewer"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = ["png"]
png = ["image/png"]
jpeg = ["image/jpeg"]
webp = ["image/webp"]
avif = ["image/avif"]
decorations = []

[dependencies]
image = { version = "0.25", default-features = false }
memmap2 = "0.9"
rustix = { version = "1", features = ["fs"] }
wayland-client = "0.31"
xkbcommon = "0.9"

[dev-dependencies]
tempfile = "3"
