# window properties
[window]
# do you want to see window title?
decorations = true
# do you want to apply antialiasing to content?
antialiasing = true

# image viewer properties
[viewer]
# minimal zoom-out value
min_scale = 0.0
# maximal zoom-in value
max_scale = 100.0
# zoom step
scale_step = 0.08
# zoom interpolation/filtering method
filter_method = "linear"

# keyboard bindings
[keybindings]
# close the application
quit = "q"
# rotate image 90 degree left
rotate_left = "["
# rotate image 90 degree right
rotate_right = "]"
